# https://python-poetry.org/docs/

[tool.poetry]
name = "feature-smartapp"
version = "0.1.0"
description = "TODO"
authors = []


[tool.poetry.dependencies]
python = ">=3.10, <3.15"

pybotx = "^0.76.5"
pybotx-smartapp-rpc = "^0.13.1"

fastapi = "^0.115.0"
uvicorn = "^0.34.0"

loguru = "^0.7.3"
mako = "~1.1.4"
python-dotenv = "^1.0.0"
pydantic-settings = "^2.0.0"

aiofiles = "^25.1.0"
types-aiofiles = "^25.1.0"

[tool.poetry.group.dev.dependencies]
black = "^25.0.0"
isort = "^5.13.0"
autoflake = "^2.0.0"
mypy = "^1.10.0"
wemake-python-styleguide = "^1.6.0"
bandit = "^1.7.2"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
