#!/bin/bash

NAME="smartapp"

function buildFront() {
  cd frontend && \
  npm i && \
  npm run build && \
  cd ..
  
  return $?
}

function moveFrontBuildToBack() {
  rm -rf ./backend/app/resources/static && \
  mv ./frontend/build ./backend/app/resources/static

  return $?
}

function buildBack() {
  REV="$(git rev-parse --short HEAD)"
  VER="$(cat ./frontend/package.json | grep "version" | grep -Eo "\d+[^\"]+")"
  TAG="${NAME}-${VER}-${REV}"

  docker build -t $TAG ./backend/ && \
  printf "DOCKER IMAGE TAG\n======================\n$TAG\n======================\n"

  return $?
}


buildFront && moveFrontBuildToBack && buildBack
