name: Smartapp application
on: push
jobs:

  lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.4"
      - name: Setup deps
        working-directory: ./backend
        run: |
          pip install -q poetry==1.5.1
          poetry config virtualenvs.in-project true
          poetry install
      - name: Run lint
        working-directory: ./backend
        run: |
          source .venv/bin/activate
          ./scripts/lint
